#!/usr/bin/env python
import sys
import json
import yaml

jsonstr = ""
for line in sys.stdin:
    jsonstr += line

print(yaml.dump(yaml.load(json.dumps(json.loads(jsonstr))), default_flow_style=False))
